/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Todo API
 * OpenAPI spec version: 1.0.0
 */
export interface Todo {
  id: string;
  title: string;
  completed: boolean;
}

export type Todos = Todo[];

export type PostTodoBody = {
  title: string;
  completed: boolean;
};
